spring:
  kafka:
    consumer:
      bootstrap-servers: cipher:9092
      registry-servers: http://cipher:8081
      group-id: events_persister
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  data:
    cassandra:
      keyspace-name: events
      contact-points: 192.168.1.100
      port: 9042

kafka:
  topics:
    event: test